target 'AiLaAi' do
  use_frameworks!
  platform :ios, '16'
  #pod 'shared', :path => '../shared'
  #pod 'models', :path => '../../ailaai-shared/models'
  #pod 'api', :path => '../../ailaai-shared/api'
  pod 'ExyteChat'
  pod 'Alamofire'
end
